client localhost {
    ipaddr = 127.0.0.1
    secret = testing123
    shortname = localhost
    nas_type = other
}

client 2950 {
    ipaddr = 10.10.30.10
    secret = <shared-secret>
    shortname = cat2950
    nas_type = cisco
}
