server:
  http_listen_port: 9080
  grpc_listen_port: 0
positions:
  filename: /tmp/positions.yaml
clients:
  - url: http://10.10.30.242:3100/loki/api/v1/push
scrape_configs:
  - job_name: network_devices
    static_configs:
      - targets:
          - localhost
        labels:
          __path__: /var/log/remote/*.log
    pipeline_stages:
      - regex:
          source: filename
          expression: '/var/log/remote/(?P<host>[^/]+)\.log'
      - template:
          source: host
          template: '{{ if or (eq . "10.10.10.1") (eq . "10.10.10.2") (eq . "10.10.20.1") (eq . "10.10.20.2") (eq . "10.10.40.1") (eq . "10.10.40.2") (eq . "192.168.100.1") (eq . "192.168.100.2") }}router{{ else }}switch{{ end }}'
          target: job
      - labels:
          host:
          job:
